# Mathematics



## Functions 

<p style = "margin-bottom: 0px; font-size: 20px; ">**Functions**</p>

- **Concept**
  - **Function** - A mathematical relational expression that maps each value of a set of inputs to a single output 
- **Related concepts**
  - **Domain** - The set of possible inputs for a function 
  - **Range** - The set of possible outputs of a function 
  - **Root** - The values of x for which the output is 0 ($f(x) = 0$)
  - **Inverse of a Function** - A function that is a reversal of another function (it reverses the subject)
- <details><summary>**Some Useful Functions**</summary>
  - **General**
    - Exponential 
    - Log and ln
    - Circle
    - Reciprocal
    - Monotonic
  - **Polynomials**
    - Linear
    - Quadratic
    - Cubic
    - Quartic
  - **Trigonometric Functions**
    - **Ordinary Trigonometric Functions**
      - Sine
      - Cosine
      - Tangent
    - **Hyperbolic Functions**
      - Hyperbolic Sine
      - Hyperbolic Cosine
      - Hyperbolic Tangent 
  - **Probability/Distributional Functions (Probability and Cumulative)**
    - **Probability Density Function**
      - Normal Distribution
      - Chi-squared Distribution
      - Log-Normal Distribution
      - Exponential Distribution
      - F Distribution
    - **Probability Mass Function**
      - Binomial Distribution
      - Poisson Distribution
      - Bernoulli Distribution
      - Rademacher Distribution </details>

<p style = "margin-bottom: 0px; font-size: 20px; ">**Polynomial Functions**</p>
- **Definition of polynomial functions**
  - The exponents of x are non-negative and is an integer 
- **Components of a polynomial functions**
  - **Variables**
    - Variables between which their relationships are described by the function 
    - **Variables** - Anything that varies in quantity 
    - Variables are denoted as y, x, or z
  - **Coefficients**
    - **Coefficient** - Constants that act as multipliers of the variables 
    - **Coefficient and the line** - Coefficients define the nature of the relationship between the input variable and the output variable 
      - **Sign of the coefficient** - The sign of the coefficient defines the direction of the relationship/graph of the function
      - **Magnitude of the coefficient** - The magnitude of the coefficient defines the magnitude of the relationship 
    - **The Leading Coefficient** - The coefficient of a variable term with the highest degree in a polynomial or the largest exponent (basically the first coefficient when the terms in the function are arranged in descending order with regards to their exponent)


<p style = "margin-bottom: 0px; font-size: 20px; ">**The Linear Function**</p>
- **The Linear Function**
  - **Concept**
    - The univariate linear function describes the output as a linear function of a variable (variable x)
    - Aka first-order polynomial 
  - **Mathematics**
    - $f(x) = ax + b$
- **The Linear Equation**
  - **Concept**
    - The univariate linear equation is an equation that describes a variable (variable y) as a linear function of another variable (variable x)
  - **Mathematics**
    - $y = ax + b$
      - ***Where***
        - $y$ 
          - Variable y (A variable represented on the y-axis)
          - This variable is usually the output, which is also called the outcome variable or the dependent variable (DV) in mathematical modelling
        - $x$ 
          - Variable x (A variable represented on the x-axis) 
          - This variable is usually the input, which is also called the predictor variable or the independent variable (IV) in mathematical modelling
        - $a$ 
          - The leading coefficient 
          - Defines the slope of the linear function
        - $b$
          - The intercept 
          

    

        
  - **Characteristics of the line**
    - **The slope**
      - **Concept**
        - The slope of the line describes the nature of the relationship between the x and the y variable 
      - 
      
- The coefficient defines the slope of the line   
          - Defines the unit by which the line is shifted vertically (along the y-axis) from the origin
          - The y coordinate of the point of the line when x = 0
          
          
          
    
- The a coefficient determines the slope of the line (the slope of the line represents the nature of the relationship )
- The sign of the a coefficient determines the direction of the slope
 - The sign of the a coefficient determines the direction of the slope
         - Positive sign ($+$)/slope - The x and y variable are positively related to each other 
    - A slope with a negative sign (or a negative slope) - The x and y variables are negatively related to each other 
  - The magnitude of the a coefficient 
  - The slope of the line describes the magnitude of the relationship between the x and y variable - That is, how strongly x and y varies together 
  

<p style = "margin-bottom: 0px; font-size: 20px; ">**The Quadratic Function**</p>  
 - **Concept**
  - The quadratic function describes the quadratic relationship between variables 
- **Mathematics**
  - $f(x) = ax^{2} + bx + c$
    - ***Where***

  
  
  
  
<p style = "margin-bottom: 0px; font-size: 20px; ">**The Cubic Function**</p>  
 - **Concept**
  - The cubic function describes the cubic relationship between variables 
- **Mathematics**
  - $f(x)= ax^{3} + bx^{2} + cx + d$
    - ***Where*** 
  
  
  
  
  
  
 <p style = "margin-bottom: 0px; font-size: 20px; ">**The Quartic Function**</p>  
 - **Concept**
  - The quartic function describes the quadratic relationship between variables 
- **Mathematics**
  - $f(x)= ax^{4} + bx^{3} + cx^{2} + dx + e$
    - ***Where*** 
  
  
  
  
<p style = "margin-bottom: 0px; font-size: 20px; ">**The Quintic Function**</p>  
 - **Concept**
  - The quintic function describes the quintic relationship between variables 
- **Mathematics**
  - $f(x) = ax^{5} + bx^{4} + cx^{3} + dx^{2} + ex + f$
    - ***Where*** 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
